on:
  push:
    branches:
      - main

jobs:
  build_and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

                    
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.CLIENT }}
          tenant-id: ${{ secrets.TENANT }}
          subscription-id: ${{ secrets.SUBSCRIPTION }}


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: farmbook85-backend980be876
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
